### ISSUE TITLE
report Cucumber Scenario results with hpqc-connector into ALM

### ISSUE THREAD

**Issue by JanDoeschner** [telekom/testerra-hpqc-connector#5]
**Background**
I am using testerra and I am writing my tests with cucumber (required by the project). I also have a Microfocus ALM to be used in the project.

**desired solution**
I need to mark the result of a test run (e.g. passed or failed) in the TestLab in ALM so I can see in the TestLab for each Test in the TestSets. Unfortunatelly the annotation based concept of the testerra-hpqc-connector does not work in cucumber. I cant place Annotations into the Feature files. So I have no way to configure the TestSet in the TestLab for each feature file.

**optional/additional requirements**
- It would be great to have a link to the test report (or even better: a direct link to the test result within the Testerra report). This way I won't need to transfer all the test artifacts into ALM.
- As cucumber has 7 test-status and ALM also knows 7 status, there could be a fixed mapping. It would me better to configure the mapping e.g. in a properties file

**Comment by JanDoeschner** [comment]
Additional Information:
Here's an Example for a Cucumber-Status to QC-Status Mapping:

```java
 switch (testStatus) {
            case "PASSED":
                qcStatus = "Passed";
                break;
            case "PENDING":
                qcStatus = "Parked";
                break;
            case "SKIPPED":
                qcStatus = "Blocked";
                break;
            case "UNDEFINED":
                qcStatus = "N/A";
                break;
            case "UNUSED":
                qcStatus = "No Run";
                break;
            case "AMBIGUOUS":
                qcStatus = "Not Completed";
                break;
            case "FAILED":
            default:
                qcStatus = "Failed";
        }
```

**Comment by gogro** [comment]
feature implementation postponed.
