### ISSUE TITLE
Please extend error handling on QcRestClient.java arround line 742

### ISSUE THREAD

**Issue by jdoeschn** [telekom/testerra-hpqc-connector#6]
**Describe the bug**
If an error occurs while creating a run via rest client, then a marshalling exception is thrown.

**To Reproduce**
1. Given I try to add a test run to a test set via QC REST Client
2. And an Error occurs
javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"QCRestException"). Erwartete Elemente sind <{}Entity>

**Expected behavior**
There should be a check for QCException and a handling for it (e.g. throw a named exception including the error text )

**Actual behavior**
The marshaller throws an exception that points only to a marshalling problem but not to the root cause.

**Additional context**
Please check nuts ;)

[main] INFO eu.tsystems.mms.tic.testframework.qcrest.clients.QcRestClient - Added run http://qualitycenter.domain.de/qcbin/rest/domains/I_V/projects/projectname/runs/123456
[main] ERROR eu.tsystems.mms.tic.testframework.qcrest.clients.QcRestClient - Error parsing TestSetTestObject to xml.
javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"QCRestException"). Erwartete Elemente sind <{}Entity>
...
at eu.tsystems.mms.tic.testframework.qcrest.clients.QcRestClient.updateTestSetTest(**QcRestClient.java:742**)
...

**Comment by jdoeschn** [comment]
I created a commit that illustrates how a solution could look like. Please check https://github.com/jdoeschn/testerra-hpqc-connector/commit/e3162cd4583557623d983758aef436bc2196d589 - please take into account, that a test for this change is missing and that I had problems with my IDE so this code snipped is even uncompiled. Please consider it only as an idea/suggestion!

**Comment by martingrossmann** [comment]
The used ALM version is newer then the ALM instance we used for develop this connector. 
We need to change the workflow how a testrun is created, details can be found here: https://lobsterautomation.wordpress.com/2017/01/18/hp-alm-rest-api/
